merge:
  # How do we domain name without specifying certificate as terraform can do?
  # https://github.com/aws/serverless-application-model/issues/783
  # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/api_gateway_domain_name
  # Domain:
  #   type: aws_api_gateway_base_path_mapping
  #   object_type: object
  #   transform: |-
  #     {
  #        DomainName: domain_name,
  #        BasePath: base_path
  #     }
  # eg:
  # resource "aws_api_gateway_base_path_mapping" "foo_deployment-base-path-mapping" {
  #     base_path            = "foo"
  #     api_id               = "${aws_api_gateway_rest_api.foo.id}"
  #     stage_name           = "dev"
  #     domain_name          = "api.dev.mydomain.com"
  #     depends_on           = [ "aws_api_gateway_deployment.foo_deployment" ]
  # }
  # instead use aws_api_gateway_base_path_mapping.yaml

  # dont think we want StageName because of: https://stackoverflow.com/questions/61341709/stage-dev-already-exists-for-aws-serverless-api-with-cloudformation
  # however AWS::Serverless::Api requires it
  StageName:
    type: aws_api_gateway_deployment
    object_type: string
    transform: stage_name

merge_exclude_types:
  - aws_api_gateway_deployment
